version: '3.8'
services:
  weather-app:
    build: .
    container_name: weather_app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-container:5432/WeatherAppDB
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=171101
    depends_on:
      - postgres-container
    networks:
      - weather-network

  postgres-container:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: WeatherAppDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 171101
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - weather-network

networks:
  weather-network:
    driver: bridge

volumes:
  postgres_data:
